### ISSUE TITLE
Web driver installation instructions?

### ISSUE THREAD

**Issue by kahliloppenheimer** [edenzik/SageGrades#3]
I installed selenium then tried to run the script but got this stack trace. Do I need to specially install the web drivers?

Traceback (most recent call last):
  File "sage.py", line 104, in <module>
    print get_grades()
  File "sage.py", line 19, in get_grades
    browser = webdriver.Firefox()
  File "/Applications/anaconda/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 77, in **init**
    self.binary, timeout),
  File "/Applications/anaconda/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in **init**
    self.binary.launch_browser(self.profile)
  File "/Applications/anaconda/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Applications/anaconda/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/Applications/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Applications/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by edenzik** [comment]
Do you have Firefox installed? You can also try the chrome driver. I
believe Firefox installed is enough, but chrome requires you to
specifically install the driver.

I'll also merge wesleys pull request that uses PhantomJS, possibly doing
away with the need for a driver at all.

**Comment by kahliloppenheimer** [comment]
Installed firefox and that fixed this error. Thanks!
